### PR TITLE
Add `cache: pip` to all setup-pythons

### PR DESCRIPTION
**Pull request by rasa**
Testing and working locally.

### CODE REVIEW

**Comment by kdeldycke** [comment]
That is a great improvement which speeds up all workflows a lot.

I even tried it in `v2.5.0`: 
- https://github.com/kdeldycke/workflows/commit/b907a9f727f149c9f0b3c1a16edd55c355199030
- https://github.com/kdeldycke/workflows/commit/1f7ae395e9b2b72397fc3f5055f985b93c752526

But I had to remove it in `v2.5.1` as it did not worked out with reuseable workflows: https://github.com/kdeldycke/workflows/commit/8017af2319805a123f43afaabf8af42760360787

I don't remember the details though. Maybe it was because I was specifying `cache-dependency-path: requirements.txt`. And of course in the repository in which I was reusing the workflow, `requirements.txt` was not found.

Maybe it is time to revisit this issue. Is your PR working in the context of reused workflow?

**Comment by rasa** [comment]
> Is your PR working in the context of reused workflow?

@kdeldycke By “reused”, do you mean where these are called by another workflow? If so, yes. I have not yet seen any failures due to the added caching. 

By failure, did you experience cache misses, or did the workflows themselves fail?

If it was only cache misses, we could add a [cache-hit](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#cache-hit) to explore this issue.

**Comment by rasa** [comment]
I'm not sure it applies here, but we can use
`cache-dependency-path: **/requirements*.txt`
to catch non-standard locations and filenames.

**Comment by kdeldycke** [comment]
> @kdeldycke By “reused”, do you mean where these are called by another workflow? If so, yes. I have not yet seen any failures due to the added caching.

Yes. *Reused* means called by another workflow. It is [GitHub's own concept](https://docs.github.com/en/actions/using-workflows/reusing-workflows).

This PR has been open for a while and I can see you are still keeping it in sync. So I'll try to merge it anyway, without the `cache-dependency-path` setting, and see how it behave in my subprojects.

**Comment by kdeldycke** [comment]
Your PR had some conflicts so I re-created it in commit: 3a53e69b2a32a108c816d0c4085a7ef5e50c80a3

We'll see how it goes from here and if this cache is introducing issues.

**Pull request closed without merging**
