### PR TITLE
Fix 3 typos

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks @rasa !

**Comment by rasa** [comment]
Btw, that’s the last of the typos. :)

**Comment by kdeldycke** [comment]
> Btw, that’s the last of the typos. :)

Keep them coming! I love your attention to details! 🤗

**Comment by rasa** [comment]
@kdeldycke I think cspell has found them all, but if others pop up, I will submit.

**Pull request merged**
