### PR TITLE
Freeze docformatter at 1.6.0.rc1

### PR DESCRIPTION
**Pull request by rasa**
As it fixes https://github.com/PyCQA/docformatter/issues/140

### CODE REVIEW

**Comment by kdeldycke** [comment]
Ahah, I did notice the `1.6.0.rc1` tag but wasn't brave enough to use it yet. But you are right, we can target it and provide feedback.

**Comment by kdeldycke** [comment]
BTW, `1.6.0.rc1` was not released on PyPi so I had to target the git repo. See: https://github.com/kdeldycke/workflows/commit/3a061368e43b824c90e26508e8942a2dc4b1e746

**Comment by rasa** [comment]
@kdeldycke Sorry to lead you astray. I just say that all the requirements except that one had `==`, but that one had `!=`. Probabbly should have changed it to `==1.4` to be safe.

**Comment by kdeldycke** [comment]
No worries @rasa, that's part of the game. The `!=` was intentional to skip the whole `1.5.*` series, while having dependabot taunt me with a PR to update to `1.6.0` as soon as it hits PyPi.

Anyway, after [starting the discussion](https://github.com/PyCQA/docformatter/issues/157) with `docformatter`'s author and reported the issue, I decided to [rely on the unreleased `1.6.0-rc*` series](https://github.com/kdeldycke/workflows/commit/d6c0e2a4169371db9c8fb44c5e5966b434572759) to feed bug reports upstream and have them fixed sooner.

**Pull request merged**
